version: '3'

networks:
  deegree:
    external: false

services:
  deegree:
    # Image built automatically on Docker Hub based on
    # https://github.com/wetransform-os/deegree-ogcapi (devel branch)
    image: wetransform/deegree-ogc-api:latest
    networks:
      - deegree
    # depends_on:
    #   - database
    ports:
      - "8080:8080"
    volumes:
    - ./workspaces:/workspaces
    environment:
    - CATALINA_OPTS=-Ddeegree.oaf.openapi.cors.allow_all=true -Ddeegree.oaf.openapi.version_path_segment=true -Ddeegree.oaf.openapi.version_response_header=true
